version: "3"
services:

  rabbit.docker:
   image: rabbitmq:3.7.8-management-alpine
   restart: always     
   hostname: rabbit.docker
   ports:
      - "15672:15672"
      - "5672:5672"
  refiner:
    image: grabid/refiner:local
    build:     
      context: ./src/Refiner
    depends_on: 
      - rabbit.docker  
    restart: always
  logger:
    image: grabid/logger:local
    build:     
      context: ./src/Logger
    depends_on: 
      - rabbit.docker  
    restart: always
  ingestion:
    image: grabid/ingestion:local
    build:      
      context: ./src/Ingestion  
    depends_on: 
      - rabbit.docker
    restart: always






    
  



